<?php

function thinkinvideo_show_video($video, $uri = '', $nid, $url = 'rtmp://www.openico.com/oflaDemo/') {
	global $user;
	$img = '';
	$result = '';
	drupal_add_js(drupal_get_path('module', 'thinkinvideo') . '/js/jwplayer.js'); // Attaches JW Player element
	if(in_array('Premium User', array_values($user->roles)) || in_array('administrator', array_values($user->roles))){
		$img = file_create_url($uri);
		$result .= '<script type="text/javascript">';
		$result .= '  jwplayer("myElement").setup({';
		/*$result .= '      modes: [';
		$result .= '          { type: "html5" },';
		$result .= '      { type: "flash", src: "'.drupal_get_path('module', 'thinkinvideo').'/js/jwplayer.flash.swf" }';
		$result .= '      ]';*/
		$result .= '      file: "' . $url . $video .'",';
		$result .= '      image: "'.$img.'",';
		$result .= '      width: "100%",';
		$result .= '      height: "56%",';
		$result .= '      rtmp: {';
		$result .= '        bufferlength: 10';
		$result .= '      }';
		$result .= '  });';
		$result .= '</script>';
	}else{
		$query=db_select('field_data_field_video_type','t')->fields('t',array('field_video_type_tid'))->condition('t.entity_id', $nid)->execute()->fetchAssoc();
		//如果是免费视频，不需要登录也能看
		if($query['field_video_type_tid'] == 16){
			$img = file_create_url($uri);
			$result .= '<script type="text/javascript">';
			$result .= '  jwplayer("myElement").setup({';
			$result .= '      file: "' . $url . $video .'",';
			$result .= '      image: "'.$img.'",';
			$result .= '      width: "100%",';
			$result .= '      height: "56%",';
			$result .= '      rtmp: {';
			$result .= '        bufferlength: 10';
			$result .= '      }';
			$result .= '  });';
			$result .= '</script>';
			
		}else{
			//$img = image_style_url('watermarking', $uri);
			$img = l('<img src="' . image_style_url('watermarking', $uri) . '"\>', 'user', array('html' => true));
			
			$result .= '<script type="text/javascript">';
			$result .= '  document.getElementById("myElement").innerHTML = \''. $img . '\';';
			$result .= '</script>';
		}
	}
	
	return $result;
}
