<?php
function thinkindup_form_user_profile_form_alter(&$form, $form_state) {
	global $user;
  if (isset($form['locale']) && $user->uid != 1) {
    if (count(element_children($form['locale'])) > 1) {
      unset($form['locale']['language']);
    }
    else {
      unset($form['locale']);
    }
  }
  if (isset($form['contact']) && $user->uid != 1) {
      unset($form['contact']);
  }
  if (isset($form['privatemsg']) && $user->uid != 1) {
      unset($form['privatemsg']);
  }
}