<?php
function thinkinusers_getrole(){
	global $user;
	$output = '<h3>'.t('User Type').'</h3>';
	if(!$user->uid){return '';}
  $roles = $user->roles; 
	$role = '<span class="badge authenticated">'.t('authenticated user').'</span>';
	if(!empty($roles[4])){$role = '<span class="badge badge-success premium">'.t('Premium User').'</span>';}
	if(!empty($roles[3])){$role = '<span class="badge badge-important administrator">'.t('administrator').'</span>';}
	$output .= '<dd>'.$role.'</dd>';
	if(!empty($roles[4])){
		$validity = thinkinusers_subscription_validity($user->uid);
		$output .= '<h3>'.t('Subscription Validity').'</h3><dd><div class="alert alert-info"><strong>'. date('Y-m-d', $validity). '</strong> ('.t('Total:'). round(($validity - time())/3600/24) . ' ' . t('days') .')</div>' .l(t('Renew Now'), 'pricing', array('html' => true,'attributes' => array('class' => array('btn btn-large btn-primary')))).'</dd>';
	}
	return $output;
}

function thinkinusers_subscription_validity($uid){
	$query = db_select('field_data_field_commerce_sp_validity','v')->fields('v')->condition('v.entity_id', $uid)->condition('v.entity_type', 'user')->execute()->fetchAssoc();
	if(empty($query['field_commerce_sp_validity_value'])){return '';}
	return $query['field_commerce_sp_validity_value'];
}